- name: Ensure neutron-server service is stopped
  service:
    name: "neutron-server"
    state: stopped
  when: inventory_hostname in groups['neutron_server']

- name: Ensure neutron-l3-agent is stopped
  service:
    name: "neutron-l3-agent"
    state: stopped
    enabled: no
  when: inventory_hostname in groups['neutron_agent']

- name: Stop openvswitch-switch service
  service:
    name: "openvswitch-switch"
    state: stopped

- name: Delete openvswitch logs
  shell: rm -rf /var/log/openvswitch/*

- name: Delete openvswitch database
  shell: rm -rf /etc/openvswitch/conf.db

- name: Start openvswitch-switch service
  service:
    name: "openvswitch-switch"
    state: started

- name: Set fact with controller IP address
  set_fact:
    odl_ip: "{{ hostvars[groups['neutron_server'][0]]['ansible_eth1']['ipv4']['address'] }}"

- name: Set Opendaylight as manager
  command: ovs-vsctl set-manager tcp:{{ odl_ip }}:6640

- name: Configure hosts for networking-odl, force kernel datapath
  command: "{{ neutron_bin }}/neutron-odl-ovs-hostconfig --noovs_dpdk"

- name: Set fact with local IP
  set_fact:
    ovs_local_ip: "{{ hostvars[inventory_hostname]['_lookup_address'] }}"

- name: Set local ip for OpenvSwitch
  command: "ovs-vsctl set Open_vSwitch . other_config:local_ip={{ ovs_local_ip }}"
