- name: Ensure neutron-server service is stopped
  service:
    name: "neutron-server"
    state: stopped
  when: inventory_hostname in groups['neutron_server']

- name: Ensure neutron-l3-agent is stopped
  service:
    name: "neutron-l3-agent"
    state: stopped
    enabled: no
  when: inventory_hostname in groups['neutron_agent']

# neutron-openvswitch-agent is only installed when ml2.ovs is set
#
#- name: Ensure neutron-openvswitch-agent is stopped
#  service:
#    name: "neutron-openvswitch-agent"
#    state: stopped
#    enabled: no
#  when: inventory_hostname in groups['neutron_agent']

- name: Stop openvswitch-switch service
  service:
    name: "openvswitch-switch"
    state: stopped
  when:
    - inventory_hostname in groups['compute_hosts']

- name: Delete openvswitch logs
  shell: rm -rf /var/log/openvswitch/*
  when:
    - inventory_hostname in groups['compute_hosts']

- name: Delete openvswitch database
  shell: rm -rf /etc/openvswitch/conf.db
  when:
    - inventory_hostname in groups['compute_hosts']

- name: Start openvswitch-switch service
  service:
    name: "openvswitch-switch"
  when:
    - inventory_hostname in groups['compute_hosts']

